# coding: utf-8

"""
    CLOUD API

    An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.lan_api import LanApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestLanApi(unittest.TestCase):
    """LanApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.lan_api.LanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datacenters_lans_delete(self):
        """Test case for datacenters_lans_delete

        Delete a Lan.  # noqa: E501
        """
        pass

    def test_datacenters_lans_find_by_id(self):
        """Test case for datacenters_lans_find_by_id

        Retrieve a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_get(self):
        """Test case for datacenters_lans_get

        List Lans  # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_find_by_id(self):
        """Test case for datacenters_lans_nics_find_by_id

        Retrieve a nic attached to lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_get(self):
        """Test case for datacenters_lans_nics_get

        List Lan Members   # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_post(self):
        """Test case for datacenters_lans_nics_post

        Attach a nic  # noqa: E501
        """
        pass

    def test_datacenters_lans_patch(self):
        """Test case for datacenters_lans_patch

        Partially modify a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_post(self):
        """Test case for datacenters_lans_post

        Create a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_put(self):
        """Test case for datacenters_lans_put

        Modify a Lan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
