# coding: utf-8

"""
    CLOUD API

    An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.  # noqa: E501

    The version of the OpenAPI document: 6.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.network_load_balancers_api import NetworkLoadBalancersApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestNetworkLoadBalancersApi(unittest.TestCase):
    """NetworkLoadBalancersApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.network_load_balancers_api.NetworkLoadBalancersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datacenters_networkloadbalancers_delete(self):
        """Test case for datacenters_networkloadbalancers_delete

        Remove an Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_find_by_network_load_balancer_id(self):
        """Test case for datacenters_networkloadbalancers_find_by_network_load_balancer_id

        Retrieve an Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_delete(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_delete

        Remove Flow Log from Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_find_by_flow_log_id(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_find_by_flow_log_id

        Retrieve a Flow Log of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_get(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_get

        List Network Load Balancer Flow Logs  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_patch(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_patch

        Partially modify a Flow Log of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_post(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_post

        Add a Network Load Balancer Flow Log  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_flowlogs_put(self):
        """Test case for datacenters_networkloadbalancers_flowlogs_put

        Modify a Flow Log of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_delete(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_delete

        Remove Forwarding Rule from Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_find_by_forwarding_rule_id(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_find_by_forwarding_rule_id

        Retrieve a Forwarding Rule of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_get(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_get

        List Network Load Balancer Forwarding Rules  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_patch(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_patch

        Partially modify a forwarding rule of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_post(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_post

        Add a Network Load Balancer Forwarding Rule  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_forwardingrules_put(self):
        """Test case for datacenters_networkloadbalancers_forwardingrules_put

        Modify a forwarding rule of the Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_get(self):
        """Test case for datacenters_networkloadbalancers_get

        List Network Load Balancers  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_patch(self):
        """Test case for datacenters_networkloadbalancers_patch

        Partially update an Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_post(self):
        """Test case for datacenters_networkloadbalancers_post

        Create an Network Load Balancer  # noqa: E501
        """
        pass

    def test_datacenters_networkloadbalancers_put(self):
        """Test case for datacenters_networkloadbalancers_put

        Update an Network Load Balancer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
