# coding: utf-8

"""
    CLOUD API

    IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.  # noqa: E501

    The version of the OpenAPI document: 6.0-SDK.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.ip_blocks_api import IPBlocksApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestIPBlocksApi(unittest.TestCase):
    """IPBlocksApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.ip_blocks_api.IPBlocksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ipblocks_delete(self):
        """Test case for ipblocks_delete

        Delete IP Block  # noqa: E501
        """
        pass

    def test_ipblocks_find_by_id(self):
        """Test case for ipblocks_find_by_id

        Retrieve an IP Block  # noqa: E501
        """
        pass

    def test_ipblocks_get(self):
        """Test case for ipblocks_get

        List IP Blocks   # noqa: E501
        """
        pass

    def test_ipblocks_patch(self):
        """Test case for ipblocks_patch

        Partially modify IP Block  # noqa: E501
        """
        pass

    def test_ipblocks_post(self):
        """Test case for ipblocks_post

        Reserve IP Block  # noqa: E501
        """
        pass

    def test_ipblocks_put(self):
        """Test case for ipblocks_put

        Modify IP Block  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
