# coding: utf-8

"""
    CLOUD API

    An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.snapshot_api import SnapshotApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestSnapshotApi(unittest.TestCase):
    """SnapshotApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.snapshot_api.SnapshotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_snapshots_delete(self):
        """Test case for snapshots_delete

        Delete a Snapshot  # noqa: E501
        """
        pass

    def test_snapshots_find_by_id(self):
        """Test case for snapshots_find_by_id

        Retrieve a Snapshot by its uuid.  # noqa: E501
        """
        pass

    def test_snapshots_get(self):
        """Test case for snapshots_get

        List Snapshots   # noqa: E501
        """
        pass

    def test_snapshots_patch(self):
        """Test case for snapshots_patch

        Partially modify a Snapshot  # noqa: E501
        """
        pass

    def test_snapshots_put(self):
        """Test case for snapshots_put

        Modify a Snapshot  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
