# coding: utf-8

"""
    CLOUD API

    IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.  # noqa: E501

    The version of the OpenAPI document: 6.0-SDK.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import ionoscloud
from ionoscloud.models.label import Label  # noqa: E501
from ionoscloud.rest import ApiException

class TestLabel(unittest.TestCase):
    """Label unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Label
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = ionoscloud.models.label.Label()  # noqa: E501
        if include_optional :
            return Label(
                id = 'urn:label:datacenter:700e1cab-99b2-4c30-ba8c-1d273ddba022:environment',
                type = 'label',
                href = '<RESOURCE-URI>',
                metadata = ionoscloud.models.no_state_meta_data.NoStateMetaData(
                    etag = '45480eb3fbfc31f1d916c1eaa4abdcc3', 
                    created_date = '2015-12-04T14:34:09.809Z', 
                    created_by = 'user@example.com', 
                    created_by_user_id = 'user@example.com', 
                    last_modified_date = '2015-12-04T14:34:09.809Z', 
                    last_modified_by = 'user@example.com', 
                    last_modified_by_user_id = '63cef532-26fe-4a64-a4e0-de7c8a506c90', ),
                properties = ionoscloud.models.label_properties.LabelProperties(
                    key = 'environment', 
                    value = 'production', 
                    resource_id = '700e1cab-99b2-4c30-ba8c-1d273ddba022', 
                    resource_type = 'datacenter', 
                    resource_href = 'https://<hostname>/datacenters/700e1cab-99b2-4c30-ba8c-1d273ddba022', )
            )
        else :
            return Label(
                properties = ionoscloud.models.label_properties.LabelProperties(
                    key = 'environment', 
                    value = 'production', 
                    resource_id = '700e1cab-99b2-4c30-ba8c-1d273ddba022', 
                    resource_type = 'datacenter', 
                    resource_href = 'https://<hostname>/datacenters/700e1cab-99b2-4c30-ba8c-1d273ddba022', ),
        )

    def testLabel(self):
        """Test Label"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
