# coding: utf-8

"""
    CLOUD API

    An enterprise-grade Infrastructure is provided as a Service (IaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.   The API allows you to perform a variety of management tasks such as spinning up additional servers, adding volumes, adjusting networking, and so forth. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive.  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.location_api import LocationApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestLocationApi(unittest.TestCase):
    """LocationApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.location_api.LocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_locations_find_by_region_id(self):
        """Test case for locations_find_by_region_id

        List Locations within a region  # noqa: E501
        """
        pass

    def test_locations_find_by_region_id_and_id(self):
        """Test case for locations_find_by_region_id_and_id

        Retrieve a Location  # noqa: E501
        """
        pass

    def test_locations_get(self):
        """Test case for locations_get

        List Locations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
