# coding: utf-8

"""
    CLOUD API

    IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.  # noqa: E501

    The version of the OpenAPI document: 6.0-SDK.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.locations_api import LocationsApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.locations_api.LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_locations_find_by_region_id(self):
        """Test case for locations_find_by_region_id

        List Locations within a region  # noqa: E501
        """
        pass

    def test_locations_find_by_region_id_and_id(self):
        """Test case for locations_find_by_region_id_and_id

        Retrieve a Location  # noqa: E501
        """
        pass

    def test_locations_get(self):
        """Test case for locations_get

        List Locations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
