# coding: utf-8

"""
    CLOUD API

    IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.  # noqa: E501

    The version of the OpenAPI document: 6.0-SDK.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ionoscloud
from ionoscloud.api.lans_api import LansApi  # noqa: E501
from ionoscloud.rest import ApiException


class TestLansApi(unittest.TestCase):
    """LansApi unit test stubs"""

    def setUp(self):
        self.api = ionoscloud.api.lans_api.LansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_datacenters_lans_delete(self):
        """Test case for datacenters_lans_delete

        Delete a Lan.  # noqa: E501
        """
        pass

    def test_datacenters_lans_find_by_id(self):
        """Test case for datacenters_lans_find_by_id

        Retrieve a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_get(self):
        """Test case for datacenters_lans_get

        List Lans  # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_find_by_id(self):
        """Test case for datacenters_lans_nics_find_by_id

        Retrieve a nic attached to lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_get(self):
        """Test case for datacenters_lans_nics_get

        List Lan Members   # noqa: E501
        """
        pass

    def test_datacenters_lans_nics_post(self):
        """Test case for datacenters_lans_nics_post

        Attach a nic  # noqa: E501
        """
        pass

    def test_datacenters_lans_patch(self):
        """Test case for datacenters_lans_patch

        Partially modify a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_post(self):
        """Test case for datacenters_lans_post

        Create a Lan  # noqa: E501
        """
        pass

    def test_datacenters_lans_put(self):
        """Test case for datacenters_lans_put

        Modify a Lan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
